global:
  scrape_interval: 15s
  evaluation_interval: 15s

  #
  # Cortex Labels
  # 
  # external_labels:
  #   cluster: site1.kristianjones.dev
  #   __replica__: '{{ env "NOMAD_ALLOC_NAME" }}'

scrape_configs:
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']


remote_write:
  - url: http://cortex-distributor-http-cont.service.kjdev:{{ env "NOMAD_PORT_distributor_http" }}/api/v1/push
    send_exemplars: true

  