global:
  scrape_interval: 15s
  evaluation_interval: 15s

  #
  # Cortex Labels
  # 
  # external_labels:
  #   cluster: site1.kristianjones.dev
  #   __replica__: '{{ env "NOMAD_ALLOC_NAME" }}'

scrape_configs:
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: fw.site1
    static_configs:
      - targets:
          - 172.16.0.1:9100
          - 172.16.0.2:9100

  - job_name: patroni
    dns_sd_configs:
      - names: 
          - patroni.service.kjdev

  - job_name: netbox
    dns_sd_configs:
      - names: 
          - netbox-http-cont.service.kjdev

  - job_name: nextcloud
    dns_sd_configs:
      - names:
          - nextcloud-prom-cont.service.kjdev

  - job_name: kea
    dns_sd_configs:
      - names: 
          - dhcp-metrics.service.kjdev

  - job_name: grafana
    #
    # TODO: mTLS
    #
    scheme: https
    tls_config:
      ca_file: /local/GrafanaCA.pem
      server_name: grafana-cont.service.kjdev
    dns_sd_configs:
      - names: 
          - grafana-cont.service.kjdev

  - job_name: loki
    dns_sd_configs:
      - names: 
          - loki-compactor-http-cont.service.kjdev
          - loki-distributor-http-cont.service.kjdev
          - loki-index-gateway-http-cont.service.kjdev
          - loki-ingester-http-cont.service.kjdev
          - loki-querier-http-cont.service.kjdev
          - loki-query-frontend-http-cont.service.kjdev
          - loki-query-scheduler-http-cont.service.kjdev

  - job_name: cortex
    dns_sd_configs:
      - names: 
          - cortex-purger-http-cont.service.kjdev
          - cortex-alertmanager-http-cont.service.kjdev
          - cortex-store-gateway-http-cont.service.kjdev
          - cortex-distributor-http-cont.service.kjdev
          - cortex-ingester-http-cont.service.kjdev
          - cortex-query-frontend-http-cont.service.kjdev
          - cortex-query-scheduler-http-cont.service.kjdev
          - cortex-ruler-http-cont.service.kjdev

  #
  # Hashicorp
  #

  #
  # Vault
  #
  
  #
  # CoreVault
  #
  - job_name: corevault.core0.site1.kristianjones.dev
    metrics_path: /v1/sys/metrics
    params:
      format: ['prometheus']

    #
    # TODO: Vault mTLS
    #
    # scheme: https
    # tls_config:
    #   ca_file: your_ca_here.pem
    
    bearer_token: "${CoreVault.Token}"
    dns_sd_configs:
      - names: 
          - CoreVault.service.dc1.kjdev


  #
  # Vault
  #
  # - job_name: vault.core0site1
  #   metrics_path: "/v1/sys/metrics"
  #   params:
  #     format: ['prometheus']
  #   scheme: https
  #   tls_config:
  #     ca_file: your_ca_here.pem
  #   bearer_token: "your_vault_token_here"
  #   dns_sd_configs:
  #     - names: 
  #         - CoreVault.service.dc1.kjdev

  
  #
  # Caches
  #

  #
  # GitHub Cache
  #
  - job_name: githubcache
    dns_sd_configs:
      - names: 
          - dhcp-metrics.service.kjdev


remote_write:
  - url: http://http.cortex-distributor.service.kjdev:8080/api/v1/push
    send_exemplars: true

  