data_dir: alloc/data/vector/

api:
  enabled: true
  address: 0.0.0.0:[[ env "NOMAD_PORT_api" ]]
  playground: true 

sources:
  logs:
    type: syslog
    address: 0.0.0.0:[[ env "NOMAD_PORT_syslog" ]]
    mode: tcp

sinks:
  loki:
    inputs:
      - logs
    type: loki
    endpoint: http://ingressweb-http-cont.service.kjdev:8080
    encoding:
      codec: json
    labels:
      host: '{{ host }}'
      level: '{{ severity }}'
      # ts: '{{ timestamp }}'
    healthcheck:
      enabled: false
    batch:
      max_bytes: 50000