data_dir: /var/lib/vector

api:
  enabled: true
  address: 0.0.0.0:[[ env "NOMAD_PORT_api" ]]
  playground: true 

sources:
  Syslog:
    type: syslog
    address: 0.0.0.0:[[ env "NOMAD_PORT_syslog" ]]
    mode: tcp

sinks:
  loki:
    inputs:
      - Syslog
    type: loki
    endpoint: http://ingressweb-http-cont.service.kjdev:8080
    encoding:
      codec: json
    labels:
      host: 'core0'
    healthcheck:
      enabled: false