global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: '${SMTP.Server}:${SMTP.Port}'
  smtp_from: '${SMTP.Username}'
  smtp_auth_username: '${SMTP.Username}'
  smtp_auth_password: '${SMTP.Password}'

route:
  # A default receiver.
  receiver: send-teams

receivers:
  - name: send-email
    email_configs:
      - to: 'me@kristianjones.dev'

  - name: send-teams
    webhook_configs:
      - url: http://alerts.msteams.service.dc1.kjdev:8089/v2/connector