ExternalURL: https://hass.int.site1.kristianjones.dev:443
InternalURL: https://homeassistant-https-cont.service.kjdev:8123


DatabaseURI: postgresql://${Database.Username}:${Database.Password}@${Database.Hostname}:${Database.Port}/${Database.Database}


MQTTHostname: ${MQTT.Connection.Hostname}
MQTTPort: ${MQTT.Connection.Port}
MQTTUsername: ${MQTT.Credentials.Username}
MQTTPassword: ${MQTT.Credentials.Password}

#
# Misc Secrets
#
HomeLatitude: ${Secrets.HomeLocation.HomeLatitude}
HomeLongitude: ${Secrets.HomeLocation.HomeLongitude}