devices:
%{ for Name, Device in Devices ~}
  - name: ${Name}
    address: ${Device.IPAddress}
    user: ${Device.Username}
    password: ${Device.Password}
%{ endfor ~}

features:
  #
  # Routing
  #
  bgp: false
  conntrack: true
  routes: true

  #
  # DHCP
  #
  dhcp: true
  dhcpv6: true
  dhcpl: true
  pools: true

  #
  # System
  #
  firmware: true
  health: true
  monitor: true

  #
  # Interfaces
  #
  optics: true
  capsman: true
  netwatch: true
