http-url: http://http.horizion.opennms.service.kjdev:8980/opennms
id: '{{ env "NOMAD_ALLOC_NAME" }}'
location: dc1

ipc:
  kafka:
    boostrap.servers: 'http.kafka.service.kjdev:9092'

telemetry:
  flows:
    single-port-listener:
      # Set to true to add single port listener config, omit or set to false to disable
      enabled: true
      # Parameters can be optionally provided
      parameters:
        # This translates to parameters.port=50000 in the generated config
        port: 9999

netmgt:
  syslog:
    syslog.listen.interface: '0.0.0.0'
    syslog.listen.port: 1514

system:
  properties:
    jaeger-agent-host: http.distributor.tempo.service.kjdev
    org.opennms.snmp.snmp4j.allowSNMPv2InV1: true

jetty:
  web:
    host: '0.0.0.0'
    port: 8080

karaf:
  shell:
    ssh:
      host: '0.0.0.0'
      port: 8201
  management:
    rmi:
      registry:
        host: '127.0.0.1'
        port: 1299
      server:
        host: '127.0.0.1'
        port: 45444
