[mattermost]
    [mattermost.core]
    Server="mattermost.int.site1.kristianjones.dev"
    Team="yourteam"
    Login="test"
    Password="yourpass"
    PrefixMessagesWithNick=true
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "