#
# Networking
#

address: 0.0.0.0:443
grpc_address: 0.0.0.0:443
metrics_address: 0.0.0.0:9443

#
# General
#
installation_id: '{{ env "NOMAD_ALLOC_NAME" }}'

#
# Pomerium Core
#

services: proxy

#
# TLS
#

autocert: false
autocert_must_staple: false

#
# mTLS
#
certificate_authority_file: /local/ServerCA.pem
certificate_file: /secrets/TLS/Server.pem
certificate_key_file: /secrets/TLS/Server.key

#
# Authenticate Service
#

authenticate_service_url: https://auth.int.site1.kristianjones.dev

idp_provider: oidc
idp_provider_url: https://auth.kristianjones.dev/application/o/pomeriumproxy-auth/
idp_client_id: ${OpenID.ClientID}
idp_client_secret: ${OpenID.ClientSecret}



#
# Secrets
#

cookie_secret: ${Secrets.CookieSecret}
shared_secret: ${Secrets.SharedSecret}

jwt_claims_headers: email,groups,user,nickname

#
# Data Broker
#
# Docs: https://www.pomerium.com/reference/#data-broker-service
#

databroker_service_url: https://https.databroker.pomerium.service.dc1.kjdev:443
databroker_storage_type: redis
databroker_storage_connection_string: 'rediss://redis.pomerium.service.kjdev:6379/0'
databroker_storage_ca_file: /local/ServerCA.pem
databroker_storage_cert_file: /secrets/TLS/Server.pem
databroker_storage_key_file: /secrets/TLS/Server.key


#
# Authorize Service
#

authorize_service_url: https://https.authorize.pomerium.service.dc1.kjdev:443
signing_key: ${Secrets.SigningKey}

#
# Proxy Service
#

#cookie_domain: int.site1.kristianjones.dev
default_upstream_timeout: 5m

# https://pomerium.com/reference/#routes
routes:
  #
  # Draw 
  #
  - from: https://drawio.int.site1.kristianjones.dev
    to: http://http.drawio.service.dc1.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  #
  # Mattermost
  #
  - from: https://mattermost.int.site1.kristianjones.dev
    to: http://mattermost-leader-http-cont.service.dc1.kjdev:8065
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  #
  # Grafana
  #
  - from: https://grafana.int.site1.kristianjones.dev
    to: https://grafana-cont.service.kjdev:443
    tls_custom_ca_file: /secrets/TLS/GrafanaCA.pem
    tls_server_name: grafana.int.site1.kristianjones.dev
    timeout: 30s
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  #
  # HomeAssistant
  #
  - from: https://hass.int.site1.kristianjones.dev
    to: https://home1-hass-home-assistant.ix-home1-hass.svc.cluster.local:8123
    tls_custom_ca_file: /secrets/TLS/HomeAssistantCA.pem
    tls_server_name: hass.int.site1.kristianjones.dev
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

  - from: https://hass-code.int.site1.kristianjones.dev
    to: http://home1-hass-home-assistant-codeserver.ix-home1-hass.svc.cluster.local:12321
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

  #
  # SABnzbd
  #
  - from: https://sabnzbd.kjmedia.stream
    to: http://kjmedia-sabnzbd.ix-kjmedia-sabnzbd.svc.cluster.local:8080
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

  #
  # Radarr
  #
  - from: https://radarr.kjmedia.stream
    to: http://kjmedia-radarr.ix-kjmedia-radarr.svc.cluster.local:8080
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

  #
  # Sonarr
  #
  - from: https://sonarr.kjmedia.stream
    to: http://kjmedia-sonarr.ix-kjmedia-sonarr.svc.cluster.local:8080
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true


  #
  # Prowlarr
  #
  - from: https://prowlarr.kjmedia.stream
    to: http://kjmedia-prowlarr.ix-kjmedia-prowlarr.svc.cluster.local:8080
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

  #
  # CyberChef
  #
  - from: https://cyberchef.int.site1.kristianjones.dev
    to: http://http.cyberchef.service.dc1.kjdev:8000
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

  #
  # ShareX
  #
  - from: https://sharex.int.site1.kristianjones.dev
    to: http://http.cyberchef.service.dc1.kjdev:8000
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

  #
  # Network
  #

  - from: https://ns.int.site1.kristianjones.dev
    to: http://http.admin.powerdns.service.kjdev
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

  - from: https://unifi.int.site1.kristianjones.dev
    to: https://kjdev-unifi.ix-kjdev-unifi.svc.cluster.local:8443
    tls_skip_verify: true
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

  #
  # NetBox
  #
  - from: https://netbox.int.site1.kristianjones.dev
    to: http://netbox-http-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true


  #
  # Servers
  #

  - from: https://nomad.int.site1.kristianjones.dev
    to: http://http.NomadServer.service.dc1.kjdev:4646
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true


  #
  # AAA
  #

  #
  # Teleport
  #

  - from: https://teleport.int.site1.kristianjones.dev
    to: https://http.proxy.teleport.service.dc1.kjdev:443
    tls_skip_verify: true
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true


#
# Tracing
#
tracing_provider: zipkin
tracing_sample_rate: 0.20
tracing_zipkin_endpoint: http://http.distributor.tempo.service.kjdev:9411

pomerium_debug: false
log_level: info
