#
# Networking
#

address: 0.0.0.0:443
grpc_address: 0.0.0.0:443
metrics_address: 0.0.0.0:9443

#
# General
#
installation_id: '{{ env "NOMAD_ALLOC_NAME" }}'

#
# Pomerium Core
#

services: databroker

#
# TLS
#

autocert: false
autocert_must_staple: false

#
# mTLS
#
certificate_authority_file: /local/ServerCA.pem
certificate_file: /secrets/TLS/Server.pem
certificate_key_file: /secrets/TLS/Server.key

#
# Authenticate Service
#

authenticate_service_url: https://auth.int.site1.kristianjones.dev
authenticate_internal_service_url: https://https.authorize.pomerium.service.dc1.kjdev:443

idp_provider: oidc
idp_provider_url: https://auth.kristianjones.dev/application/o/pomeriumproxy-auth/
idp_service_account: '${ServiceAccount}'
idp_client_id: ${OpenID.ClientID}
idp_client_secret: ${OpenID.ClientSecret}

#
# Secrets
#

cookie_secret: ${Secrets.CookieSecret}
shared_secret: ${Secrets.SharedSecret}

jwt_claims_headers: email,groups,user,nickname

#
# Data Broker
#
# Docs: https://www.pomerium.com/reference/#data-broker-service
#

databroker_service_url: https://https.databroker.pomerium.service.dc1.kjdev:443
databroker_storage_type: redis
databroker_storage_connection_string: 'rediss://redis.pomerium.service.kjdev:6379/0'
databroker_storage_ca_file: /local/ServerCA.pem
databroker_storage_cert_file: /secrets/TLS/Server.pem
databroker_storage_key_file: /secrets/TLS/Server.key


#
# Authorize Service
#
authorize_service_url: https://https.authorize.pomerium.service.dc1.kjdev:443
signing_key: ${Secrets.SigningKey}

#
# Proxy Service
#

#cookie_domain: int.site1.kristianjones.dev
default_upstream_timeout: 5m

# https://pomerium.com/reference/#routes
#routes:

#
# Tracing
#
tracing_provider: zipkin
tracing_sample_rate: 0.20
tracing_zipkin_endpoint: http://http.distributor.tempo.service.kjdev:9411

pomerium_debug: false
log_level: info
