#
# Draw
#
- from: https://drawio.int.site1.kristianjones.dev
  to: http://http.drawio.service.dc1.kjdev:8080
  allow_any_authenticated_user: true
  pass_identity_headers: true
  allow_websockets: true

#
# Mattermost
#
- from: https://teams.int.mylogin.space
  to: http://http.mattermost.service.kjdev:8080
  preserve_host_header: true
  allow_public_unauthenticated_access: true
  pass_identity_headers: true
  allow_websockets: true

- from: https://teams-ws.int.mylogin.space
  to: http://http.mattermost.service.kjdev:80
  preserve_host_header: true
  allow_public_unauthenticated_access: true
  pass_identity_headers: true
  allow_websockets: true

#
# Grafana
#
- from: https://grafana.int.mylogin.space
  to: https://grafana-cont.service.kjdev:443
  tls_custom_ca_file: /secrets/TLS/GrafanaCA.pem
  tls_server_name: grafana.int.site1.kristianjones.dev
  timeout: 30s
  allow_any_authenticated_user: true
  pass_identity_headers: true
  allow_websockets: true

#
# HomeAssistant
#

- from: https://hass.int.mylogin.space
  to: https://home1-hass-home-assistant.ix-home1-hass.svc.cluster.local:8123
  tls_custom_ca_file: /secrets/TLS/HomeAssistantCA.pem
  tls_server_name: hass.int.site1.kristianjones.dev
  allowed_idp_claims:
    groups:
      - Home Users
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

- from: https://controlcenter.house
  to: https://home1-hass-home-assistant.ix-home1-hass.svc.cluster.local:8123
  tls_custom_ca_file: /secrets/TLS/HomeAssistantCA.pem
  tls_server_name: hass.int.site1.kristianjones.dev
  allowed_idp_claims:
    groups:
      - Home Users
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

- from: https://hass-code.int.mylogin.space
  to: http://home1-hass-home-assistant-codeserver.ix-home1-hass.svc.cluster.local:12321
  allowed_idp_claims:
    groups:
      - Home Admins
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

#
# SABnzbd
#
- from: https://sabnzbd.kjmedia.stream
  to: http://kjmedia-sabnzbd.ix-kjmedia-sabnzbd.svc.cluster.local:8080
  preserve_host_header: true
  allowed_idp_claims:
    groups:
      - Media Admins
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

#
# Radarr
#
- from: https://radarr.kjmedia.stream
  to: http://kjmedia-radarr.ix-kjmedia-radarr.svc.cluster.local:8080
  preserve_host_header: true
  allowed_idp_claims:
    groups:
      - Media Admins
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

#
# Sonarr
#
- from: https://sonarr.kjmedia.stream
  to: http://kjmedia-sonarr.ix-kjmedia-sonarr.svc.cluster.local:8080
  preserve_host_header: true
  allowed_idp_claims:
    groups:
      - Media Admins
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

#
# Prowlarr
#
- from: https://prowlarr.kjmedia.stream
  to: http://kjmedia-prowlarr.ix-kjmedia-prowlarr.svc.cluster.local:8080
  preserve_host_header: true
  allowed_idp_claims:
    groups:
      - Media Admins
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

#
# Komga
#
- from: https://komga.kjmedia.stream
  to: http://kjmedia-komga.ix-kjmedia-komga.svc.cluster.local:8080
  preserve_host_header: true
  pass_identity_headers: true
  allow_public_unauthenticated_access: true
  allow_websockets: true
  cors_allow_preflight: true

#
# Readarr
#
- from: https://readarr.kjmedia.stream
  to: http://kjmedia-readarr.ix-kjmedia-readarr.svc.cluster.local:8080
  preserve_host_header: true
  allowed_idp_claims:
    groups:
      - Media Consumers
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

#
# BookSonic
#


#
# CyberChef
#

- from: https://cyberchef.int.mylogin.space
  to: http://http.cyberchef.service.dc1.kjdev:8000
  preserve_host_header: true
  allow_any_authenticated_user: true
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

#
# Network
#

- from: https://ns.int.site1.kristianjones.dev
  to: http://http.admin.powerdns.service.kjdev
  preserve_host_header: true
  allowed_idp_claims:
    groups:
      - Servers
      - Network
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

- from: https://ns.int.mylogin.space
  to: http://http.admin.powerdns.service.kjdev
  preserve_host_header: true
  allowed_idp_claims:
    groups:
      - Servers
      - Network
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

- from: https://unifi.int.mylogin.space
  to: https://kjdev-unifi.ix-kjdev-unifi.svc.cluster.local:8443
  tls_skip_verify: true
  preserve_host_header: true
  allowed_idp_claims:
    groups:
      - Servers
      - Network
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

#
# NetBox
#

- from: https://netbox.int.mylogin.space
  to: http://http.netbox.service.kjdev:8080
  allowed_idp_claims:
    groups:
      - Servers
      - Network
  pass_identity_headers: true

- from: https://ipam.ipaddr.network
  to: http://http.netbox.service.kjdev:8080
  allowed_idp_claims:
    groups:
      - Servers
      - Network
  pass_identity_headers: true

############
#  Search  #
############

- from: https://opensearch.int.mylogin.space
  to: http://https.dashboard.opensearch.service.kjdev:5601
  allowed_idp_claims:
    groups:
      - Servers
      - Network
  pass_identity_headers: true

############
# Security #
############

- from: https://threatmapper.int.mylogin.space
  to: http://http.web.threatmapper.service.kjdev:8080
  allowed_idp_claims:
    groups:
      - Servers
  pass_identity_headers: true

#
# ThreatMapper
#

#
# Servers
#

- from: https://nomad.int.mylogin.space
  to: http://http.NomadServer.service.dc1.kjdev:4646
  preserve_host_header: true
  allowed_idp_claims:
    groups:
      - Servers
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

- from: https://hashui.int.mylogin.space
  to: http://http.hashui.service.dc1.kjdev:8000
  preserve_host_header: true
  allowed_idp_claims:
    groups:
      - Server Admins
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

#
# Consul
# 

- from: https://consul.int.mylogin.space
  to: http://consul.service.kjdev:8500
  preserve_host_header: true
  allowed_idp_claims:
    groups:
      - Server Admins
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

#
# Vault
#

- from: https://vault.int.mylogin.space
  to: http://vault.service.kjdev:8100
  preserve_host_header: true
  allowed_idp_claims:
    groups:
      - Server Admins
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

#
# CoreVault
#

- from: https://corevault.int.mylogin.space
  to: http://covault.service.kjdev:8200
  preserve_host_header: true
  allowed_idp_claims:
    groups:
      - Server Admins
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true

#
# OpenNMS
#
- from: https://nms.int.mylogin.space
  to: http://http.horizion.opennms.service.kjdev:8980
  preserve_host_header: true
  allowed_idp_claims:
    groups:
      - Server Admins
  pass_identity_headers: true
  allow_websockets: true
  cors_allow_preflight: true


#
# AAA
#
