#
# Networking
#

address: 0.0.0.0:443
grpc_address: 0.0.0.0:443

#
# Pomerium Core
#

services: databroker

#
# TLS
#

autocert: false
autocert_must_staple: false

#
# mTLS
#
certificate_authority_file: /local/ServerCA.pem
certificate_file: /secrets/TLS/Server.pem
certificate_key_file: /secrets/TLS/Server.key

#
# Authenticate Service
#

authenticate_service_url: https://auth.int.site1.kristianjones.dev

idp_provider: oidc
idp_provider_url: https://auth.kristianjones.dev/application/o/pomeriumproxy-auth/
idp_client_id: ${OpenID.ClientID}
idp_client_secret: ${OpenID.ClientSecret}

#
# Secrets
#

cookie_secret: ${Secrets.CookieSecret}
shared_secret: ${Secrets.SharedSecret}

jwt_claims_headers: email,groups,user,nickname

#
# Data Broker
#
# Docs: https://www.pomerium.com/reference/#data-broker-service
#

databroker_service_url: https://https.databroker.pomerium.service.dc1.kjdev:443
databroker_storage_type: redis
databroker_storage_connection_string: 'rediss://redis.pomerium.service.kjdev:6379/0'
databroker_storage_ca_file: /local/ServerCA.pem
databroker_storage_cert_file: /secrets/TLS/Server.pem
databroker_storage_key_file: /secrets/TLS/Server.key


#
# Authorize Service
#
authorize_service_url: https://https.authorize.pomerium.service.dc1.kjdev:443
signing_key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1tM2JCOXZKZi94V25vQzlVTFBTTlFhZUlHcW9LYzNsaEFBU0VPZzFFRkFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMWs5bG5wYmdUMXBSZERjK3JYWmRYQU9TSzE5di9xYUdxRmIwSmxNb2t0S0YwblBLWFVYWAo2QjZKY3JmY09vc2RvTEZkZ2ROQW9NNGRzUmVmenVTaVlRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=

#
# Proxy Service
#

#cookie_domain: int.site1.kristianjones.dev
default_upstream_timeout: 5m

# https://pomerium.com/reference/#routes
routes:
routes:
  #
  # NetBox
  #
  - from: https://netbox.int.site1.kristianjones.dev
    to: http://netbox-http-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true

  #
  # NextCloud
  #
  - from: https://nextcloud.int.site1.kristianjones.dev
    to: http://nextcloud-web-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  #
  # Draw 
  #
  - from: https://drawio.int.site1.kristianjones.dev
    to: http://http.drawio.service.dc1.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  #
  # Mattermost
  #
  - from: https://mattermost.int.site1.kristianjones.dev
    to: http://mattermost-leader-http-cont.service.dc1.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  #
  # Grafana
  #
  - from: https://grafana.int.site1.kristianjones.dev
    to: https://grafana-cont.service.kjdev:443
    tls_custom_ca_file: /secrets/TLS/GrafanaCA.pem
    tls_server_name: grafana.int.site1.kristianjones.dev
    timeout: 30s
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  #
  # HomeAssistant
  #
  - from: https://hass.int.site1.kristianjones.dev
    to: https://172.31.241.2:36006
    tls_custom_ca_file: /secrets/TLS/HomeAssistantCA.pem
    tls_server_name: hass.int.site1.kristianjones.dev
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

  #
  # OpenProject
  #
  - from: https://openproject.int.site1.kristianjones.dev
    to: http://proxy.openproject.service.dc1.kjdev:80
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

  #
  # GitLab
  #
  - from: https://gitlab.int.site1.kristianjones.dev
    to: http://https.workhorse.gitlab.service.dc1.kjdev:443
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

  #
  # SABnzbd
  #
  - from: https://sabnzbd.kjmedia.stream
    to: http://kjmedia-sabnzbd.ix-kjmedia-sabnzbd.svc.cluster.local:8080
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

  #
  # Radarr
  #
  - from: https://radarr.kjmedia.stream
    to: http://kjmedia-radarr.ix-kjmedia-radarr.svc.cluster.local:8080
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

  #
  # Sonarr
  #
  - from: https://sonarr.kjmedia.stream
    to: http://kjmedia-sonarr.ix-kjmedia-sonarr.svc.cluster.local:8080
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true


  #
  # Prowlarr
  #
  - from: https://prowlarr.kjmedia.stream
    to: http://kjmedia-prowlarr.ix-kjmedia-prowlarr.svc.cluster.local:8080
    preserve_host_header: true
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
    cors_allow_preflight: true

#
# Tracing
#
tracing_provider: zipkin
tracing_sample_rate: 0.20
tracing_zipkin_endpoint: http://http.distributor.tempo.service.kjdev:9411

pomerium_debug: false
log_level: info
