#
# PRODUCTION
#
production:
  main:
    adapter: postgresql
    encoding: unicode
    database: ${Database.Database}
    username: ${Database.Username}
    password: ${Database.Password}
    host: ${Database.Hostname}
    port: ${Database.Port}
    # load_balancing:
    #   hosts:
    #     - host1.example.com
    #     - host2.example.com
    #   discover:
    #     nameserver: 1.2.3.4
    #     port: 8600
    #     record: secondary.postgresql.service.consul
    #     interval: 300

#
# Development specific
#
development:
  main:
    adapter: postgresql
    encoding: unicode
    database: ${Database.Database}
    username: ${Database.Username}
    password: ${Database.Password}
    host: ${Database.Hostname}
    port: ${Database.Port}
    variables:
      statement_timeout: 15s

#
# Staging specific
#
staging:
  main:
    adapter: postgresql
    encoding: unicode
    database: ${Database.Database}
    username: ${Database.Username}
    password: ${Database.Password}
    host: ${Database.Hostname}
    port: ${Database.Port}

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  main:
    adapter: postgresql
    encoding: unicode
    database: ${Database.Database}
    username: ${Database.Username}
    password: ${Database.Password}
    host: ${Database.Hostname}
    port: ${Database.Port}
    prepared_statements: false
    variables:
      statement_timeout: 15s