kind: github
version: v3
metadata:
  # connector name that will be used with `tsh --auth=github login`
  name: github
spec:
  # Client ID of Github OAuth app
  client_id: ${OpenID.ClientID}
  # Client secret of Github OAuth app
  client_secret: ${OpenID.ClientSecret}
  # Connector display name that will be shown on web UI login screen
  display: Github
  # Callback URL that will be called after successful authentication
  redirect_url: https://localhost:3080/v1/webapi/github/callback
  teams_to_logins:
    - organization: github # Github organization name
      team: justice-league # Github team name within that organization
      # maps octocats/admins to teleport role access
      logins:
        - access