agent:
  listen:
    address: ':8085'
    websocket: true

  kubernetes_api:
    listen:
      address: ':8154'

gitlab:
  address: http://https.workhorse.gitlab.service.dc1.kjdev:443 # required
  authentication_secret_file: /secrets/.gitlab_kas_secret # required

observability:
  listen:
    address: ':8151'

redis:
  server:
    address: "redis.gitlab.service.dc1.kjdev:6379" # required

api:
  listen:
    address: ':8080'
    authentication_secret_file: /secrets/.gitlab_kas_secret # required

private_api:
  listen:
    address: ':8155'
    authentication_secret_file: /secrets/.gitlab_kas_secret
