# See detailed configuration settings : https://www.pomerium.com/docs/reference/

address: 0.0.0.0:443
grpc_address: 0.0.0.0:8443

services: authenticate

#
# TLS
#

#
# mTLS
#
#override_certificate_name: 'pomerium-authenticate-cont.service.kjdev'
certificate_authority_file: /local/ca.pem
certificate_file: /local/cert.pem
certificate_key_file: /local/cert.key
#xff_num_trusted_hops: 6

# this is the domain the identity provider will callback after a user authenticates
authenticate_service_url: https://pomerium.kristianjones.dev:443

##################################################################################
# Identity provider settings : https://www.pomerium.com/docs/identity-providers/ #
# The keys required in this section vary depending on your IdP. See the          #
# appropriate docs for your IdP to configure Pomerium accordingly.               #
##################################################################################
idp_provider_url: https://auth.kristianjones.dev/application/o/pomeriumproxy-auth
idp_provider: oidc
idp_client_id: ${OpenID.ClientID}
idp_client_secret: ${OpenID.ClientSecret}

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
cookie_secret: V2JBZk0zWGtsL29UcFUvWjVDWWQ2UHExNXJ0b2VhcDI=
shared_secret: aDducXQzK2tPY3R4TmdqTGhaYS80eGYxcTUvWWJDb2M=

jwt_claims_headers: email,groups,user,preferred_username,nickname

#
# Databroker
#
databroker_service_url: https://pomerium-databroker-cont.service.kjdev:8443
databroker_storage_type: redis
databroker_storage_connection_string: 'redis://pomerium-redis-cont.service.kjdev:6379/0'
databroker_storage_tls_skip_verify: true


authorize_service_url: https://pomerium-authorize-cont.service.kjdev:8443

# https://pomerium.com/reference/#routes
routes:
  - from: https://netbox.kristianjones.dev
    to: http://netbox-http-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://nextcloud.kristianjones.dev
    to: http://nextcloud-web-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://chat.kristianjones.dev
    to: http://mattermost-leader-http-cont.service.kjdev:8065
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://mattermost.kristianjones.dev
    to: http://mattermost-leader-http-cont.service.kjdev:8065
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

#
# Tracing
# 

tracing_provider: zipkin
tracing_sample_rate: 1
tracing_zipkin_endpoint: http://tempo-distributor-http-cont.service.kjdev:9411

pomerium_debug: true
log_level: debug
