#
# Networking
#
grpc_address: ':443'

#
# Pomerium Core
#
services: authorize

#
# TLS
#
autocert: false
autocert_must_staple: false

#
# mTLS
#
certificate_authority_file: /local/ca.pem
certificate_file: /local/cert.pem
certificate_key_file: /local/cert.key

#
# Authenticate Service
#

authenticate_service_url: https://auth.int.site1.kristianjones.dev:443/

#
# Secrets
#

cookie_secret: 'V2JBZk0zWGtsL29UcFUvWjVDWWQ2UHExNXJ0b2VhcDI='
shared_secret: 'aDducXQzK2tPY3R4TmdqTGhaYS80eGYxcTUvWWJDb2M='

jwt_claims_headers: email,groups,user,preferred_username,nickname

#
# Data Broker
#
# Docs: https://www.pomerium.com/reference/#data-broker-service
#
databroker_service_url: https://pomerium-databroker-cont.service.kjdev:443
databroker_storage_type: redis
databroker_storage_connection_string: 'redis://pomerium-redis-cont.service.kjdev:6379/0'
databroker_storage_tls_skip_verify: true

#
# Authorize Service
#
authorize_service_url: https://pomerium-authorize-cont.service.kjdev:443

idp_provider: oidc
idp_provider_url: https://auth.kristianjones.dev/application/o/pomeriumproxy-auth
idp_scopes: oidc,profile,email
idp_refresh_directory_interval: 2m
idp_client_id: ${OpenID.ClientID}
idp_client_secret: ${OpenID.ClientSecret}

#
# Proxy Service
#

cookie_domain: int.site1.kristianjones.dev
default_upstream_timeout: 5m

# https://pomerium.com/reference/#routes
routes:
  - from: https://auth.int.site1.kristianjones.dev
    to: https://pomerium-authenticate-cont.service.kjdev:443
    preserve_host_header: true
    allow_public_unauthenticated_access: true

  - from: https://netbox.int.site1.kristianjones.dev
    to: http://netbox-http-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true

#
# Tracing
#
pomerium_debug: false
log_level: info
