#
# Networking
#
address: 0.0.0.0:443
grpc_address: 0.0.0.0:8443

#
# Pomerium Core
#
services: authorize

envoy_admin_address: 0.0.0.0:9123

#
# TLS
#

#
# mTLS
#
certificate_authority_file: /local/ca.pem
certificate_file: /local/cert.pem
certificate_key_file: /local/cert.key
#xff_num_trusted_hops: 2

#
# Authenticate Service
#

authenticate_service_url: https://auth.int.site1.kristianjones.dev:443

idp_provider_url: https://auth.kristianjones.dev/application/o/pomeriumproxy-auth
idp_provider: oidc
idp_client_id: ${OpenID.ClientID}
idp_client_secret: ${OpenID.ClientSecret}

#
# Secrets
#

cookie_secret: V2JBZk0zWGtsL29UcFUvWjVDWWQ2UHExNXJ0b2VhcDI=
shared_secret: aDducXQzK2tPY3R4TmdqTGhaYS80eGYxcTUvWWJDb2M=

jwt_claims_headers: email,groups,user,preferred_username,nickname

#
# Data Broker
#
# Docs: https://www.pomerium.com/reference/#data-broker-service
#
databroker_service_url: https://pomerium-databroker-cont.service.kjdev:8443
databroker_storage_type: redis
databroker_storage_connection_string: 'redis://pomerium-redis-cont.service.kjdev:6379/0'
databroker_storage_tls_skip_verify: true

#
# Authorize Service
#

authorize_service_url: https://pomerium-authorize-cont.service.kjdev:8443

#
# Proxy Service
#

cookie_domain: int.site1.kristianjones.dev

# https://pomerium.com/reference/#routes
routes:
  - from: https://netbox.int.site1.kristianjones.dev
    to: http://netbox-http-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://nextcloud.int.site1.kristianjones.dev
    to: http://nextcloud-web-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://chat.int.site1.kristianjones.dev
    to: http://mattermost-leader-http-cont.service.kjdev:8065
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://mattermost.int.site1.kristianjones.dev
    to: http://mattermost-leader-http-cont.service.kjdev:8065
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

#
# Tracing
# 

tracing_provider: zipkin
tracing_sample_rate: 1
tracing_zipkin_endpoint: http://tempo-distributor-http-cont.service.kjdev:9411

pomerium_debug: true
log_level: debug
