# See detailed configuration settings : https://www.pomerium.com/docs/reference/

address: ':8080'
grpc_address: ':8080'

services: authorize

insecure_server: true
grpc_insecure: true

# this is the domain the identity provider will callback after a user authenticates
authenticate_service_url: https://pomerium.kristianjones.dev

idp_provider_url: https://auth.kristianjones.dev/application/o/pomeriumproxy-auth/
idp_provider: oidc
idp_client_id: ${OpenID.ClientID}
idp_client_secret: ${OpenID.ClientSecret}

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
shared_secret: V2JBZk0zWGtsL29UcFUvWjVDWWQ2UHExNXJ0b2VhcDI=

jwt_claims_headers: email,groups,user,preferred_username,nickname

# https://pomerium.com/reference/#routes
routes:
  - from: https://grafana.kristianjones.dev
    to: http://grafana-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://netbox.kristianjones.dev
    to: http://netbox-http-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://nextcloud.kristianjones.dev
    to: http://nextcloud-web-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://chat.kristianjones.dev
    to: http://mattermost-leader-http-cont.service.kjdev:8065
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://mattermost.kristianjones.dev
    to: http://mattermost-leader-http-cont.service.kjdev:8065
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true