#
# Networking
#
address: ':443'

#
# Pomerium Core
#
services: proxy

#
# TLS
#
autocert: false
autocert_must_staple: false

#
# mTLS
#
certificate_authority_file: /local/ca.pem
certificate_file: /local/cert.pem
certificate_key_file: /local/cert.key

#
# Authenticate Service
#

authenticate_service_url: https://auth.int.site1.kristianjones.dev/

default_upstream_timeout: 5m

#
# Secrets
#

cookie_secret: 'V2JBZk0zWGtsL29UcFUvWjVDWWQ2UHExNXJ0b2VhcDI='
shared_secret: 'aDducXQzK2tPY3R4TmdqTGhaYS80eGYxcTUvWWJDb2M='

jwt_claims_headers: email,groups,user,preferred_username,nickname

#
# Data Broker
#
# Docs: https://www.pomerium.com/reference/#data-broker-service
#
databroker_service_url: https://pomerium-databroker-cont.service.kjdev:443

#
# Authorize Service
#

authorize_service_url: https://pomerium-authorize-cont.service.kjdev:443

#
# Proxy Service
#

cookie_domain: int.site1.kristianjones.dev

#codec_type: http2

# https://pomerium.com/reference/#routes
routes:
  - from: https://auth.int.site1.kristianjones.dev
    to: https://pomerium-authenticate-cont.service.kjdev:443
    preserve_host_header: true
    allow_public_unauthenticated_access: true
    time: 5m


  - from: https://netbox.int.site1.kristianjones.dev
    to: http://netbox-http-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true

#
# Tracing
#
pomerium_debug: false
log_level: debug
