#
# Networking
#
grpc_address: ':443'

#
# Pomerium Core
# 
services: databroker

#
# TLS
#
autocert: false
autocert_must_staple: false

#
# mTLS
#
certificate_authority_file: /local/ca.pem
certificate_file: /local/cert.pem
certificate_key_file: /local/cert.key

#
# Authenticate Service
#

authenticate_service_url: https://auth.int.site1.kristianjones.dev/
idp_provider: oidc
idp_provider_url: http://authentik-cont.service.kjdev:9000/application/o/pomeriumproxy-auth
idp_scopes: oidc,profile,email
idp_refresh_directory_interval: 2m
idp_client_id: ${OpenID.ClientID}
idp_client_secret: ${OpenID.ClientSecret}

#
# Secrets
#

cookie_secret: 'V2JBZk0zWGtsL29UcFUvWjVDWWQ2UHExNXJ0b2VhcDI='
shared_secret: 'aDducXQzK2tPY3R4TmdqTGhaYS80eGYxcTUvWWJDb2M='

jwt_claims_headers: email,groups,user,preferred_username,nickname

#
# Data Broker
#
# Docs: https://www.pomerium.com/reference/#data-broker-service
#
databroker_service_url: https://pomerium-databroker-cont.service.kjdev:443
databroker_storage_type: redis
databroker_storage_connection_string: 'redis://pomerium-redis-cont.service.kjdev:6379/0'
databroker_storage_tls_skip_verify: true

#
# Authorize Service
#

authorize_service_url: https://pomerium-authorize-cont.service.kjdev:443
signing_key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1tM2JCOXZKZi94V25vQzlVTFBTTlFhZUlHcW9LYzNsaEFBU0VPZzFFRkFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMWs5bG5wYmdUMXBSZERjK3JYWmRYQU9TSzE5di9xYUdxRmIwSmxNb2t0S0YwblBLWFVYWAo2QjZKY3JmY09vc2RvTEZkZ2ROQW9NNGRzUmVmenVTaVlRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=

#
# Proxy Service
#

cookie_domain: int.site1.kristianjones.dev

#codec_type: http2

# https://pomerium.com/reference/#routes
routes:
  - from: https://auth.int.site1.kristianjones.dev
    to: https://pomerium-authenticate-cont.service.kjdev:443
    preserve_host_header: true
    allow_public_unauthenticated_access: true

  - from: https://netbox.int.site1.kristianjones.dev
    to: http://netbox-http-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true

#
# Tracing
#
pomerium_debug: false
log_level: info
