# See detailed configuration settings : https://www.pomerium.com/docs/reference/

#
# General
#

address: 0.0.0.0:8080
grpc_address: 0.0.0.0:8085

services: {{ env "NOMAD_META_Service" }}

#
# TODO: mTLS
#
insecure_server: true
grpc_insecure: true

#
# Authenticate Service
#

# this is the domain the identity provider will callback after a user authenticates
authenticate_service_url: https://pomerium.kristianjones.dev
authenticate_callback_path: /oauth2/callback

##################################################################################
# Identity provider settings : https://www.pomerium.com/docs/identity-providers/ #
# The keys required in this section vary depending on your IdP. See the          #
# appropriate docs for your IdP to configure Pomerium accordingly.               #
##################################################################################
idp_provider_url: https://auth.kristianjones.dev/application/o/pomeriumproxy-auth/
idp_provider: oidc
idp_client_id: ${OpenID.ClientID}
idp_client_secret: ${OpenID.ClientSecret}

#
# Secrets
#
cookie_secret: ${Secrets.CookieSecret}
shared_secret: ${Secrets.SharedSecret}

#
# Proxy Service
#
authorize_service_urls:
  - http://0.pomerium-authorize-grpc-cont.service.kjdev:8085
  - http://1.pomerium-authorize-grpc-cont.service.kjdev:8085
  - http://2.pomerium-authorize-grpc-cont.service.kjdev:8085

#
# Data Broker
#
databroker_service_urls:
  - http://0.pomerium-databroker-grpc-cont.service.kjdev:8085
  - http://1.pomerium-databroker-grpc-cont.service.kjdev:8085
  - http://2.pomerium-databroker-grpc-cont.service.kjdev:8085

databroker_storage_type: redis

databroker_storage_connection_string: redis://pomerium-redis.service.kjdev:6379/0



jwt_claims_headers: email,groups,user,preferred_username,nickname

# https://pomerium.com/reference/#routes
routes:
  - from: https://grafana.kristianjones.dev
    to: http://grafana-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://netbox.kristianjones.dev
    to: http://netbox-http-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://nextcloud.kristianjones.dev
    to: http://nextcloud-web-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://chat.kristianjones.dev
    to: http://mattermost-leader-http-cont.service.kjdev:8065
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://mattermost.kristianjones.dev
    to: http://mattermost-leader-http-cont.service.kjdev:8065
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true
