# See detailed configuration settings : https://www.pomerium.com/docs/reference/

grpc_address: :443

services: databroker

client_ca_file: /local/CA.pem

certificate_file: /local/cert.pem
certificate_key_file: /local/cert.key

override_certificate_name: 'pomerium-databroker-cont.service.kjdev'

idp_provider_url: https://auth.kristianjones.dev/application/o/pomeriumproxy-auth/
idp_provider: oidc
idp_client_id: ${OpenID.ClientID}
idp_client_secret: ${OpenID.ClientSecret}

shared_secret: aDducXQzK2tPY3R4TmdqTGhaYS80eGYxcTUvWWJDb2M=

jwt_claims_headers: email,groups,user,preferred_username,nickname

databroker_service_url: https://pomerium-databroker-cont.service.kjdev:443
authorize_service_url: https://pomerium-authorize-cont.service.kjdev:443

codec_type: http1

routes:
  - from: https://grafana.kristianjones.dev
    to: http://grafana-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://netbox.kristianjones.dev
    to: http://netbox-http-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://nextcloud.kristianjones.dev
    to: http://nextcloud-web-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://chat.kristianjones.dev
    to: http://mattermost-leader-http-cont.service.kjdev:8065
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://mattermost.kristianjones.dev
    to: http://mattermost-leader-http-cont.service.kjdev:8065
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

#
# Tracing
# 

tracing_provider: zipkin
tracing_zipkin_endpoint: http://tempo-distributor-http-cont.service.kjdev:9411