# See detailed configuration settings : https://www.pomerium.com/docs/reference/

address: 0.0.0.0:443
grpc_address: 0.0.0.0:443

services: proxy

envoy_admin_address: 0.0.0.0:9123

#
# TLS
#

#autocert: false

#
# mTLS
#
certificate_authority_file: /local/CA.pem
certificate_file: /local/cert.pem
certificate_key_file: /local/cert.key

#override_certificate_name: 'pomerium-proxy-cont.service.kjdev'
xff_num_trusted_hops: 1


#
# Authenticate Service
#

# this is the domain the identity provider will callback after a user authenticates
authenticate_service_url: https://pomerium.kristianjones.dev

##################################################################################
# Identity provider settings : https://www.pomerium.com/docs/identity-providers/ #
# The keys required in this section vary depending on your IdP. See the          #
# appropriate docs for your IdP to configure Pomerium accordingly.               #
##################################################################################
idp_provider_url: https://auth.kristianjones.dev/application/o/pomeriumproxy-auth/
idp_provider: oidc
idp_client_id: ${OpenID.ClientID}
idp_client_secret: ${OpenID.ClientSecret}

#
# Secrets
#

cookie_secret: V2JBZk0zWGtsL29UcFUvWjVDWWQ2UHExNXJ0b2VhcDI=
shared_secret: aDducXQzK2tPY3R4TmdqTGhaYS80eGYxcTUvWWJDb2M=

jwt_claims_headers: email,groups,user,preferred_username,nickname

#
# Data Broker Service 
#

databroker_service_url: https://pomerium-databroker-cont.service.kjdev:443

#
# Authorize Service
#

authorize_service_url: https://pomerium-authorize-cont.service.kjdev:443

#
# Proxy Service
#

#codec_type: http1

# https://pomerium.com/reference/#routes
routes:
  - from: https://grafana.kristianjones.dev
    to: http://grafana-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://netbox.kristianjones.dev
    to: http://netbox-http-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://nextcloud.kristianjones.dev
    to: http://nextcloud-web-cont.service.kjdev:8080
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://chat.kristianjones.dev
    to: http://mattermost-leader-http-cont.service.kjdev:8065
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

  - from: https://mattermost.kristianjones.dev
    to: http://mattermost-leader-http-cont.service.kjdev:8065
    allowed_domains:
      - kristianjones.dev
    pass_identity_headers: true
    allow_websockets: true

#
# Tracing
# 

tracing_provider: zipkin
tracing_sample_rate: 1
tracing_zipkin_endpoint: http://tempo-distributor-http-cont.service.kjdev:9411

pomerium_debug: true
log_level: debug
