listen_addr = "0.0.0.0:8080"

# [tls]
# certificate_path = '/home/git/cert.cert'
# key_path = '/home/git/key.pem'

[logging]
format = "json"
level = "debug"

[auth]
token = '${Praefect.Token}'


[replication]
batch_size = 10 # configures the number of replication jobs to dequeue and lock in a batch


# [reconciliation]
# # Duration value specifying an interval at which to run the automatic repository reconciler.
# # Automatic reconciliation is disabled if set to 0. Example: "1m" for reconciliation every minute.
# scheduling_interval = 0 
# # Scheduling duration histogram buckets.
# histogram_buckets = [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5, 10] 

[failover]
enabled = true


[[virtual_storage]]
name = 'default'

[[virtual_storage.node1]]
storage = 'kjdev-gitaly1'
address = 'tcp://kjdev-gitaly1-custom-app.ix-kjdev-gitaly1.svc.cluster.local:8075'
token = "gitalytokengitalytoken"

[[virtual_storage.node2]]
storage = 'kjdev-gitaly2'
address = 'tcp://kjdev-gitaly2-custom-app.ix-kjdev-gitaly2.svc.cluster.local:8075'
token = "gitalytokengitalytoken"


[database]
host = '${Database.Hostname}'
port = ${Database.Port}
user = '${Database.Username}'
password = '${Database.Password}'
dbname = '${Database.Database}'
sslmode = 'disable'