listen_addr = '0.0.0.0:8080'

prometheus_listen_addr = '0.0.0.0:9090'

[auth]
token = '${PraefectToken}'
transitioning = false


[[virtual_storage]]
name = 'default'

[[virtual_storage.infra1site1]]
storage = 'default'
address = 'tcp://kjdev-gitaly1-custom-app.ix-kjdev-gitaly1.svc.cluster.local:8075'
token = "gitalytokengitalytoken"

[database]
host = '${Database.Hostname}'
port = ${Database.Port}
user = '${Database.Username}'
password = '${Database.Password}'
dbname = '${Database.Database}'
sslmode = 'disable'