listen_addr = '0.0.0.0:8080'

prometheus_listen_addr = '0.0.0.0:9000'

[auth]
token = '${PraefectToken}'
transitioning = false


[[virtual_storage]]
name = 'default'

[[virtual_storage.node]]
storage = 'default'
address = 'tcp://kjdev-gitaly1-custom-app.ix-kjdev-gitaly1.svc.cluster.local:8075'
token = "gitalytokengitalytoken"

[[virtual_storage.node2]]
storage = 'default'
address = 'tcp://kjdev-gitaly2-custom-app.ix-kjdev-gitaly2.svc.cluster.local:8075'
token = "gitalytokengitalytoken"

[[virtual_storage.node3]]
storage = 'default'
address = 'tcp://172.31.241.2:37075'
token = "gitalytokengitalytoken"


[database]
host = '${Database.Hostname}'
port = ${Database.Port}
user = '${Database.Username}'
password = '${Database.Password}'
dbname = '${Database.Database}'
sslmode = 'disable'