# Optional. Setting to true enables multitenancy and requires X-Scope-OrgID header on all requests.
multitenancy_enabled: false

target: {{ env "NOMAD_META_TARGET" }}

server:
  #
  # HTTP Server
  #
  http_listen_address: 0.0.0.0
  http_listen_port: 8080

  #
  # GRPC Server
  #
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 8085

  #
  # Metrics
  #
  register_instrumentation: true

  #
  # Logs
  #
  # Output log messages in the given format. Valid formats: [logfmt, json]
  # CLI flag: -log.format
  log_format: json

  # Only log messages with the given severity or above. Valid levels: [debug, info, warn, error]
  # CLI flag: -log.level
  log_level: warn

  # Optionally log the source IPs.
  # CLI flag: -server.log-source-ips-enabled
  log_source_ips_enabled: false

  # Header field storing the source IPs. Only used if
  # server.log-source-ips-enabled is true. If not set the default Forwarded,
  # X-Real-IP and X-Forwarded-For headers are used
  # CLI flag: -server.log-source-ips-header
  #log_source_ips_header: ''

  # Regex for matching the source IPs. Only used if server.log-source-ips-enabled
  # is true. If not set the default Forwarded, X-Real-IP and X-Forwarded-For
  # headers are used
  # CLI flag: -server.log-source-ips-regex
  #log_source_ips_regex: ''

distributor:
  search_tags_deny_list:
    - "instance"
    - "version"
  receivers:
    jaeger:                            # the receives all come from the OpenTelemetry collector.  more configuration information can
      protocols:                       # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver
        thrift_http:                   #
        grpc:                          # for a production deployment you should only enable the receivers you need!
        thrift_binary:
        thrift_compact:
    zipkin:
    otlp:
      protocols:
        http:
        grpc:
    opencensus:
      
  ring:
    kvstore:
      store: consul
      prefix: ${Consul.Prefix}/collectors/

      #
      # Docs: https://cortexmetrics.io/docs/configuration/configuration-file/#consul_config
      #
      consul:
        host: ${Consul.Hostname}:${Consul.Port}
        acl_token: ${Consul.Token}

querier:
  max_concurrent_queries: 500
  frontend_worker:
    #scheduler_address: 0.tempo-query-scheduler-grpc-cont.service.kjdev:8085,1.tempo-query-scheduler-grpc-cont.service.kjdev:8085,2.tempo-query-scheduler-grpc-cont.service.kjdev:8085
    frontend_address: tempo-query-frontend-grpc-cont.service.kjdev:8085

query_frontend:
  query_shards: 20
  #scheduler_address: 0.tempo-query-scheduler-grpc-cont.service.kjdev:8085,1.tempo-query-scheduler-grpc-cont.service.kjdev:8085,2.tempo-query-scheduler-grpc-cont.service.kjdev:8085

#
# Docs: https://cortexmetrics.io/docs/configuration/configuration-file/#ingester_client_config
#
ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    grpc_compression: gzip

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m 
  lifecycler:
    # We want to start immediately.
    join_after: 0
    final_sleep: 0s
    num_tokens: 512

    ring:
      kvstore:
        store: consul
        prefix: ${Consul.Prefix}/collectors/

        #
        # Docs: https://cortexmetrics.io/docs/configuration/configuration-file/#consul_config
        #
        consul:
          host: ${Consul.Hostname}:${Consul.Port}
          acl_token: ${Consul.Token}
      replication_factor: 2


storage:
  trace:
    backend: s3
    s3:
      endpoint: ${S3.Connection.Endpoint}
      bucket: ${S3.Bucket}
      access_key: ${S3.Credentials.AccessKey}
      secret_key: ${S3.Credentials.SecretKey}
      insecure: true

    pool:
      max_workers: 100                 # worker pool determines the number of parallel requests to the object store backend
      queue_depth: 10000

compactor:
  compaction:
    compaction_window: 1h              # blocks in this time window will be compacted together
    max_block_bytes: 100_000_000       # maximum size of compacted blocks
    block_retention: 1h
    compacted_block_retention: 10m
  ring:
    kvstore:
      store: consul
      prefix: ${Consul.Prefix}/collectors/

      #
      # Docs: https://cortexmetrics.io/docs/configuration/configuration-file/#consul_config
      #
      consul:
        host: ${Consul.Hostname}:${Consul.Port}
        acl_token: ${Consul.Token}

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  node_name: {{ env "NOMAD_ALLOC_NAME" }}

overrides:
  per_tenant_override_config: /local/overrides.yaml