#
# Cluster
#

cluster.name: CoreOpenSearch

#
# Discovery
# #

# cluster.initial_master_nodes:
#   - 0.https.master.opensearch.service.kjdev
#   - 1.https.master.opensearch.service.kjdev
#   - 2.https.master.opensearch.service.kjdev

node.roles: ['{{ env "NOMAD_META_NodeType" | toLower  }}']

#
# Node
#
node.name: '{{ env "NOMAD_ALLOC_INDEX" }}.https.{{ env "NOMAD_META_NodeType" | toLower }}.opensearch.service.kjdev'

#
# Misc
#
bootstrap.memory_lock: true

discovery.seed_hosts: 
  - 0.https.master.opensearch.service.kjdev
  - 1.https.master.opensearch.service.kjdev
  - 2.https.master.opensearch.service.kjdev
  - 0.https.ingest.opensearch.service.kjdev
  - 1.https.ingest.opensearch.service.kjdev
  - 2.https.ingest.opensearch.service.kjdev

discovery.type: single-node


network.host: 0.0.0.0

plugins:
  security:
    ssl:
      transport:
        pemcert_filepath: TLS/{{ env "NOMAD_META_NodeType" }}/{{ env "NOMAD_META_NodeType" }}{{ env "NOMAD_ALLOC_INDEX" }}.pem
        pemkey_filepath: TLS/{{ env "NOMAD_META_NodeType" }}/{{ env "NOMAD_META_NodeType" }}{{ env "NOMAD_ALLOC_INDEX" }}.key
        pemtrustedcas_filepath: TLS/CA.pem
        enforce_hostname_verification: true
      http:
        enabled: true
        pemcert_filepath: TLS/{{ env "NOMAD_META_NodeType" }}/{{ env "NOMAD_META_NodeType" }}{{ env "NOMAD_ALLOC_INDEX" }}.pem
        pemkey_filepath: TLS/{{ env "NOMAD_META_NodeType" }}/{{ env "NOMAD_META_NodeType" }}{{ env "NOMAD_ALLOC_INDEX" }}.key
        pemtrustedcas_filepath: TLS/CA.pem
        enforce_hostname_verification: true
    nodes_dn:
      - CN=0.https.master.opensearch.service.kjdev
      - CN=1.https.master.opensearch.service.kjdev
      - CN=2.https.master.opensearch.service.kjdev
      - CN=0.https.ingest.opensearch.service.kjdev
      - CN=1.https.ingest.opensearch.service.kjdev
      - CN=2.https.ingest.opensearch.service.kjdev
      - CN=0.https.data.opensearch.service.kjdev
      - CN=1.https.data.opensearch.service.kjdev
      - CN=2.https.data.opensearch.service.kjdev
      - CN=3.https.data.opensearch.service.kjdev
      - CN=4.https.data.opensearch.service.kjdev
      - CN=5.https.data.opensearch.service.kjdev

    allow_default_init_securityindex: true
    audit.type: internal_opensearch
    enable_snapshot_restore_privilege: true
    check_snapshot_restore_write_privileges: true
    restapi:
      roles_enabled: ["all_access", "security_rest_api_access"]
    system_indices:
      enabled: true
      indices:
        [
          ".opendistro-alerting-config",
          ".opendistro-alerting-alert*",
          ".opendistro-anomaly-results*",
          ".opendistro-anomaly-detector*",
          ".opendistro-anomaly-checkpoints",
          ".opendistro-anomaly-detection-state",
          ".opendistro-reports-*",
          ".opendistro-notifications-*",
          ".opendistro-notebooks",
          ".opendistro-asynchronous-search-response*",
        ]

# s3.client.default.protocol: http
# s3.client.default.endpoint: ${S3.CoreRepo.Connection.Endpoint}
# s3.client.default.access_key: ${S3.CoreRepo.Credentials.AccessKey}
# s3.client.default.secret_key: ${S3.CoreRepo.Credentials.SecretKey}