version: 0.1

log:
  level: debug
  fields:
    service: gitlabregistry

storage:
  s3:
    region: us-east-1
    bucket: ${S3.Bucket}
    accesskey: ${S3.Credentials.AccessKey}
    secretkey: ${S3.Credentials.SecretKey}
    regionendpoint: ${S3.Connection.Endpoint}
    secure: false
    v4auth: true
  cache:
    layerinfo: redis
  maintenance:
    uploadpurging:
      enabled: false
  redirect:
    disable: true

redis:
  addr: redis.harbor.service.dc1.kjdev:6379
  db: 0
  pool:
    maxidle: 100
    maxactive: 500
    idletimeout: 60s

http:
  addr: 0.0.0.0:5443
  secret: helloworld
  tls:
    certificate: /secrets/TLS/Cert.pem
    key: /secrets/TLS/Cert.key
  debug:
    addr: 0.0.0.0:9090
    prometheus:
      enabled: true
      path: /metrics

auth:
  token:
    issuer: gitlab-issuer
    realm: https://git.writemy.codes/jwt/auth
    service: container_registry
    rootcertbundle: /secrets/TLS/Cert.pem

validation:
  disabled: true

compatibility:
  schema1:
    enabled: true
