version: 0.1

log:
  level: debug
  fields:
    service: gitlabregistry

storage:
  s3:
    region: us-east-1
    bucket: ${S3.Bucket}
    accesskey: ${S3.Credentials.AccessKey}
    secretkey: ${S3.Credentials.SecretKey}
    regionendpoint: ${S3.Connection.Endpoint}
    secure: false
    v4auth: true
  cache:
    layerinfo: redis
  maintenance:
    uploadpurging:
      enabled: false
  redirect:
    disable: true

external_redis:
  host: redis.registry.harbor.service.dc1.kjdev:6379
  registry_db_index: 0
  jobservice_db_index: 1
  chartmuseum_db_index: 2
  pool:trivy_db_index: 3

http:
  addr: 0.0.0.0:5443
  secret: helloworld
  tls:
    certificate: /secrets/TLS/Cert.pem
    key: /secrets/TLS/Cert.key
  debug:
    addr: 0.0.0.0:9090
    prometheus:
      enabled: true
      path: /metrics

auth:
  token:
    issuer: gitlab-issuer
    realm: https://gitlab.kristianjones.dev/jwt/auth
    service: container_registry
    rootcertbundle: /local/CA.pem

validation:
  disabled: true

compatibility:
  schema1:
    enabled: true
